name: pushstream
description: PushStream Flutter SDK for real-time messaging
version: 1.0.0
homepage: https://pushstream.ceylonitsolutions.online

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^2.4.0
  http: ^1.1.0
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
